whr/store/urls.py
from django.urls import path
from .views import *

urlpatterns=[
   path('', loginUser, name='loginUser'),
   path('main/',index,name='home'),
   path('out/',UserOut,name='UserOut'),
   path ('docs/',DocMenu,name='DocMenu'),
   path ('sprav/',SpravMenu,name='SpravMenu'),
   path('report/', ReportMenu, name='ReportMenu'),
   # Справочник единиц измерения
   path('unit/', UnitList, name='UnitList'),
   #path('unit/<str:pk>',UnitUpdate,name='UnitUpdate'),
   #path('unitdelete/<str:pk>', UnitDelete, name='UnitDelete'),
   # Справочник категорий
   path('category/', CategoryList, name='CategoryList'),

# Справочник поставщиков
   path('postav/', PostavList, name='PostavList'),


# Справочник списания
   path('spis/', SpisList, name='SpisList'),

# Справочник подразделения
   path('podraz/', PodrazList, name='PodrazList'),

# Справочник подотчетники
   path('fio/', FioList, name='FioList'),

# Справочник номенклатура
   path('SprNom/', SprNom, name='SprNom'),
   path('NomSave/',NomSave,name='NomSave'),

# Справочник объекты
   path('obct/', ObctList, name='ObctList'),


# Обработка ошибки удаления
   path('error/', ErrorDelete, name='ErrorDelete'),
# сохранение данных справочников через AJAX
   path('spr_Save/',SprSave,name='SprSave'),
   path('category_save/',SaveCategory,name='SaveCategory'),
   path('postav_save/',SavePostav,name='SavePostav'),
   path('spis_save/',SaveSpis,name='SaveSpis'),
   path('podraz_save/',SavePodraz,name='SavePodraz'),
   path('fio_save/',SaveFio,name='SaveFio'),
   path('SaveObct/',SaveObct,name='SaveObct'),
   path('podraz_save2/', SavePodraz2, name='SavePodraz2'),

# удаление строк из справочников
   path('SprDelete/',SprDelete,name='SprDelete'),
   path('CatDelete/',CatDelete,name='CatDelete'),
   path('PodrazDelete/',PodrazDelete,name='PodrazDelete'),
   path('FioDelete/',FioDelete,name='FioDelete'),
   path('PostavDelete/',PostavDelete,name='PostavDelete'),
   path('FioDelete/',FioDelete,name='FioDelete'),
   path('SpisDelete/',SpisDelete,name='SpisDelete'),
   path('ObctDelete/',ObctDelete,name='ObctDelete'),
   path('NomDelete/',NomDelete,name='NomDelete'),

# Редактирование справочников
   path('SprUpdate/',SprUpdate,name='SprUpdate'),
   path('CatUpdate/',CatUpdate,name='CatUpdate'),
   path('PodrazUpdate/',PodrazUpdate,name='PodrazUpdate'),
   path('PostavUpdate/',PostavUpdate,name='PostavUpdate'),
   path('FioUpdate/',FioUpdate,name='FioUpdate'),
   path('SpisUpdate/',SpisUpdate,name='SpisUpdate'),
   path('ObctUpdate/',ObctUpdate,name='ObctUpdate'),
   path('NomUpdate/',NomUpdate,name='NomUpdate'),
   path('NomAddUnit/', NomAddUnit, name='NomAddUnit'),
   path('NomAddCat/', NomAddCat, name='NomAddCat'),

#Документы
   path('NewOstDoc/',NewOstDoc,name='NewOstDoc'),
   path('StringOstSave/', StringOstSave, name='StringOstSave'),
   path('JurnalOst/', JurnalOst, name='JurnalOst'),
   path('AddStringOst/<str:pk>',AddStringOst,name='AddStringOst'),
   path('ReturnToJurnalOst/',ReturnToJurnalOst,name='ReturnToJurnalOst'),
   path('EditOstDoc/',EditOstDoc,name='EditOstDoc'),
   path('DeleteOstStringTable/',DeleteOstStringTable,name='DeleteOstStringTable'),
   path('UpdateOstStringTable/',UpdateOstStringTable,name='UpdateOstStringTable'),
   path('DeleteOstDoc/',DeleteOstDoc,name='DeleteOstDoc'),

   # Поступление ТМЦ//////////////////////////////////////////////////////
   path('JurnalPost/',JurnalPost,name='JurnalPost'), #Журнал документов поступление
   path('AddStringPost/<str:pk>',AddStringPost,name='AddStringPost'), #Добавление строк в новый документ
   path('ReturnToJurnalPost/', ReturnToJurnalPost, name='ReturnToJurnalPost'),#сохранение и возврат в журнад
   path('EditPostDoc/',EditPostDoc,name='EditPostDoc'),
   # Добавление номенклатуры из документа
   path('AddNomFromDoc/',AddNomFromDoc,name='AddNomFromDoc',)
]

whr/whr/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from whr import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

whr/store/models.py
from django.db import models
from django.utils import timezone
# Create your models here.//
class Unit(models.Model):
    title = models.CharField(max_length=100,verbose_name='Наименование',unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name='Единица измерения'
        verbose_name_plural='Единицы измерения'
        ordering=['title',]


# Категории
class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='Наименование категории',unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name='Категория'
        verbose_name_plural='Категории'
        ordering=['title',]

    # Поставщики
class Postav(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование компании',unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'
        ordering = ['title', ]

# Причины списания
class Spis(models.Model):
    title = models.CharField(max_length=150, verbose_name='Причина списания', unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Причина списания'
        verbose_name_plural = 'Причины списания'
        ordering = ['title', ]

# Подразделения
class Podraz(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название подразделения', unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Подразделение'
        verbose_name_plural = 'Подразделения'
        ordering = ['title', ]

    # Подотчетники
class Fio(models.Model):
    title = models.CharField(max_length=150, verbose_name='Подотчетное лицо',unique=True )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Подочтетное лицо'
        verbose_name_plural = 'Подотчетные лица'
        ordering = ['title', ]

# Объекты
class Obct(models.Model):
    title = models.CharField(max_length=150, verbose_name='Объект',unique=True )
    podraz=models.ForeignKey(Podraz,verbose_name='Подразделение',on_delete=models.PROTECT)
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'
        ordering = ['podraz','title', ]

class Nom(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование', unique=True )
    izm=models.ForeignKey(Unit,verbose_name='Ед.изм.',on_delete=models.PROTECT)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.PROTECT)
    srok=models.IntegerField(blank=True,default=0)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Создан')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Номенклатура'
        verbose_name_plural = 'Номенклатура'
        ordering = ['title', ]

class Jurnal(models.Model):
    oper=models.IntegerField(verbose_name="Код операции")
    nomerdoc=models.CharField(max_length=50,verbose_name='Номер документа')
    datadoc=models.DateTimeField(verbose_name='Дата документа')
    postav=models.ForeignKey(Postav,verbose_name='Поставщик',on_delete=models.PROTECT)
    obct=models.ForeignKey(Obct,verbose_name='Объект',on_delete=models.PROTECT)
    podraz=models.ForeignKey(Podraz,verbose_name='Подразделение',on_delete=models.PROTECT)
    fio=models.ForeignKey(Fio,verbose_name='Подотчет',on_delete=models.PROTECT)
    spis=models.ForeignKey(Spis,blank=True,null=True,verbose_name='Причина списания',on_delete=models.PROTECT)
    summa=models.FloatField(verbose_name='Сумма',default=0)
    nds=models.IntegerField(verbose_name='НДС',default=20)
    summawithnds=models.FloatField(verbose_name='Сумма с НДС',default=0)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Создан')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')



    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'
        ordering = ['-datadoc', ]



class JurnalDoc(models.Model):

    oper=models.IntegerField(max_length=1,verbose_name='Операция')
    iddoc=models.ForeignKey(Jurnal,on_delete=models.PROTECT)
    title=models.ForeignKey(Nom,verbose_name='Наименование',on_delete=models.PROTECT)
    price=models.FloatField(verbose_name='Цена',default=0.0)
    kol = models.FloatField(verbose_name='Цена', default=0.0)
    podraz=models.ForeignKey(Podraz,on_delete=models.PROTECT,verbose_name='Подразделение')
    postav=models.ForeignKey(Postav,on_delete=models.PROTECT,verbose_name='Поставщик')
    obct=models.ForeignKey(Obct,on_delete=models.PROTECT,verbose_name='Объект')
    fio=models.ForeignKey(Fio,on_delete=models.PROTECT,verbose_name='Подотчетник')
    spis=models.ForeignKey(Spis,on_delete=models.PROTECT,null=True,blank=True,verbose_name='Причина списания')
    summa=models.FloatField(verbose_name='Сумма')
    nds=models.IntegerField(default=20,verbose_name='НДС')
    summawithnds=models.FloatField(verbose_name='Сумма с НДС')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Создан')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')
    uniqfield=models.CharField(max_length=250,verbose_name='Слаг')
    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'Табличная часть'
        verbose_name_plural = 'Табличные части'
        ordering = ['-created_at', ]

whr/store/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import AuthenticationForm

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя',widget=forms.TextInput(attrs={'class':'form-control loginform'}))
    password = forms.CharField(label='Пароль',widget=forms.PasswordInput(attrs={'class':'form-control loginform' }))

class UnitForm(forms.ModelForm):
   class Meta:
      model = Unit
      fields = ['title']
      widgets = {
      'title': forms.TextInput(attrs={'class':'form-control','id':'idtitle'}),

      }

class UnitFormSprav(forms.ModelForm):
   class Meta:
      model = Unit
      fields = ['title']
      widgets = {
      'title': forms.TextInput(attrs={'class': 'form-control', 'style': 'width:200px;'}),
      }
   #def __init__(self, *args, **kwargs):
    #   super(UnitForm, self).__init__(*args, **kwargs)
     #  self.fields['title'].label = ""
class CategoryForm(forms.ModelForm):
   class Meta:
      model = Category
      fields = ['title']
      widgets = {
      'title': forms.TextInput(attrs={'class':'form-control','style':'width:955px;','id':'idtitle'}),
      }

class PostavForm(forms.ModelForm):
   class Meta:
      model = Postav
      fields = ['title']
      widgets = {
      'title': forms.TextInput(attrs={'class':'form-control','style':'width:955px;','id':'idtitle'}),
      }

class SpisForm(forms.ModelForm):
   class Meta:
      model = Spis
      fields = ['title']
      widgets = {
      'title': forms.TextInput(attrs={'class':'form-control','style':'width:955px;','id':'idtitle'}),
      }

class PodrazForm(forms.ModelForm):
   class Meta:
      model = Podraz
      fields = ['title']
      widgets = {
    'title': forms.TextInput(attrs={'class': 'form-control', 'style':'width:955px;','id':'idtitle'}),
         }
class PodrazForm2(forms.ModelForm):
   class Meta:
      model = Podraz
      fields = ['title']
      widgets = {
    'title': forms.TextInput(attrs={'class': 'form-control', 'style':'width:460px;','id':'idtitle2'}),
         }
class FioForm(forms.ModelForm):
   class Meta:
      model = Fio
      fields = ['title']
      widgets = {
    'title': forms.TextInput(attrs={'class': 'form-control', 'style':'width:955px;','id':'idtitle'}),
         }

class ObctForm(forms.ModelForm):
   class Meta:
      model = Obct
      fields = ['title','podraz']
      widgets = {
    'title': forms.TextInput(attrs={'class': 'form-control', 'id':'idtitle'}),
    'podraz': forms.Select(attrs={'class': 'form-control', 'id': 'idpodraz'}),
         }

class NomForm(forms.ModelForm):
   class Meta:
      model = Nom
      fields = '__all__'
      widgets = {
    'title': forms.TextInput(attrs={'class': 'form-control', 'id':'idtitle'}),
    'izm': forms.Select(attrs={'class': 'form-control','id':'idizm'}),
    'category': forms.Select(attrs={'class': 'form-control', 'id':'idcat'}),
     'srok': forms.TextInput(attrs={'class': 'form-control text-center', 'id':'idsrok'}),
         }


class UnitForm2(forms.ModelForm):
    class Meta:
        model = Unit
        fields = ['title']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'style': 'width:460px;', 'id': 'idtitle2'}),
        }


class CategoryForm2(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'style': 'width:460px;', 'id': 'idtitle3'}),
        }
class MyDateInput(forms.DateInput):
   input_type = 'date'
   format = '%d-%m-%Y'
class DocForm(forms.ModelForm):
   class Meta:
      model = Jurnal
      fields = ['nomerdoc','datadoc','postav','podraz','fio','obct','summa','nds','summawithnds',
                'oper']
      widgets = {
    'nomerdoc': forms.TextInput(attrs={'class': 'form-control','id':'id_nomerdoc'}),
    'datadoc': MyDateInput(attrs={'id':'id_datadoc'}),
    'postav': forms.Select(attrs={'id':'id_postav','style':"visibility:hidden;"}),
    'podraz': forms.Select(attrs={'id':'id_podraz','style':"visibility:hidden;"}),
    'fio': forms.Select(attrs={'id': 'id_fio','value':5,'style':"visibility:hidden;"}),
    'obct': forms.Select(attrs={'id': 'id_obct','value':180,'style':"visibility:hidden;"}),
    'summa': forms.NumberInput(attrs={'id': 'id_summa','value':0.0}),
    'nds': forms.NumberInput(attrs={'id': 'id_nds','value':20}),
    'summawithnds': forms.NumberInput(attrs={'id': 'id_summawithnds','value':0.0}),
    'oper':forms.NumberInput(attrs={'id':'id_oper','value':1,'style':"visibility:hidden;"})
         }

class JurnalForm(forms.ModelForm):
   class Meta:
      model = JurnalDoc
      fields = ['title','price','summa','nds','summawithnds','oper','iddoc','podraz',
                'postav','obct','fio','spis','uniqfield']
      widgets = {
    'title': forms.Select(attrs={'class': 'form-control','id':'id_title'}),
    'price': forms.NumberInput(attrs={'class':'form-control','id': 'id_price'}),
    'summa': forms.NumberInput(attrs={'class': 'form-control', 'id': 'id_summa2'}),
    'nds': forms.NumberInput(attrs={'class': 'form-control', 'id': 'id_nds2'}),
    'summawithnds': forms.NumberInput(attrs={'class': 'form-control', 'id': 'id_summawithnds2'}),
    'oper':forms.HiddenInput(attrs={'id':'id_oper2'}),
    'iddoc':forms.HiddenInput(attrs={'id':'id_iddoc2'}),
    'podraz': forms.HiddenInput(attrs={'id': 'id_podraz2'}),
    'postav': forms.HiddenInput(attrs={'id': 'id_postav2'}),
    'obct': forms.HiddenInput(attrs={'id': 'id_obct2'}),
    'fio': forms.HiddenInput(attrs={'id': 'id_fio2'}),
    'spis': forms.HiddenInput(attrs={'id': 'id_spis2'}),
    'uniqfield': forms.HiddenInput(attrs={'id': 'id_uniqfield'}),
         }

class OstDocForm(forms.ModelForm):
    class Meta:
        model=Jurnal
        fields = ['nomerdoc', 'datadoc', 'postav', 'podraz', 'fio', 'obct', 'summa', 'nds', 'summawithnds',
                  'oper']
        widgets = {
            'nomerdoc': forms.TextInput(attrs={'class': 'form-control', 'id': 'id_nomerdoc','style':'text-align:right;border-color: grey'}),
            'datadoc': MyDateInput(attrs={'id': 'id_datadoc','style':'height:40px;border-radius:4px;border-color: grey'}),
            'postav': forms.HiddenInput(attrs={'id': 'id_postav','value':9, 'style': "visibility:hidden;"}),
            'podraz': forms.HiddenInput(attrs={'id': 'id_podraz', 'value':74,'style': "visibility:hidden;"}),
            'fio': forms.HiddenInput(attrs={'id': 'id_fio', 'value': 5, 'style': "visibility:hidden;"}),
            'obct': forms.HiddenInput(attrs={'id': 'id_obct', 'value': 180, 'style': "visibility:hidden;"}),
            'summa': forms.HiddenInput(attrs={'id': 'id_summa', 'value': 0.0,'style': "visibility:hidden;"}),
            'nds': forms.HiddenInput(attrs={'id': 'id_nds', 'value': 20,'style': "visibility:hidden;"}),
            'summawithnds': forms.HiddenInput(attrs={'id': 'id_summawithnds', 'value': 0.0,'style': "visibility:hidden;"}),
            'oper': forms.HiddenInput(attrs={'id': 'id_oper', 'value': 1, 'style': "visibility:hidden;"})
        }

class Ost(forms.Form):
    nomerdoc=forms.NumberInput()
    datadoc=MyDateInput()

whr/store/templates/store/Doc/AddStringOst.html
{% extends 'store/menu.html' %}
{% load static %}
{% block DataArea %}

<div class="row">


<div class="col-md-12 mx-auto shadow">

<table class=" table shadow table-hover ">
<thead class="bg-primary text-light">
<tr>
<th  style="width:60%" >Документ начальных остатков</th>
<th style="width:13; " class=" text-end "> Номер документа </th>
<th style="width:10%;" class=" text-end" >Дата документа</th>

<th style="width:10%;" class=" text-end"></th>
</tr>
</thead>
    <form method="post" id="ost-form2" >
 {% csrf_token %}

<tr>
    <td><input  type="hidden" id="id_iddoc" value="{{docost.id}} " ></td>
        <td  class=" text-end" ><input type="text" id="id_nomerdoc" class="form-control" style="text-align:right" required value="{{docost.nomerdoc}}"></td>
        <td "class="text-end pb-3"> <input type="date" id="id_datadoc" class="form-control" style="text-align:right" required value="{{docost.datadoc|date:'Y-m-d'}}"></td>

        <td class=" text-end"> <button type="submit" class="btn  btn-dark btn-sm mb-1 " id="returnJurOst">Сохранить</button></td>
    </form>
    </tr>
</table >

 <div class="scrolltable">
    <table class=" table  shadow table-bordered table-hover" style="width:100%" >

        <form id="ost-string-form" method="post">
             {% csrf_token %}
            <input  type="hidden" id="id_string" value="" >
            <thead class="bg-primary">
            <th style="width:40%" class="text-light" >Наименование, ед.изм.</th>

             <th  class="text-end text-light " style="width:10%" >Цена</th>
             <th  class="text-end text-light" style="width:10%"  >Кол-во</th>
             <th  class="text-end text-light" style="width:10%">Сумма</th>
             <th class="text-end  text-light" style="width:10%" >НДС</th>
            <th class="text-end text-light" style="width:10%" >Сумма с НДС</td>
            <th></th>
            </thead>
<tr>

       <td ><div class="input-group">
                   <select name="title" id="idtitle" class="form-control  " required >
            <option selected></option>
            {% for item in nom %}
            <option value="{{item.id}}">{{item.title}}, {{item.izm}}</option>
            {% endfor %}
       </select>
                    <div class=" input-group-button pr-2">
                        <button type="button" id="show-contact-modal-button" class="btn btn-secondary mr-2" style="margin-left: 5px;" data-bs-toggle="modal" data-bs-target="#ModalNomPodbor">...</button>
                    </div>
                </div>


          </td>

           <td> <input type="number" id="idprice" class="form-control text-end" step="any" required min="0" >
        </td></td>

         <td><input type="number" id="idkol" class="form-control text-end" step="any" required min="0">
        </td>

       <td> <input type="number" id="idsumma" class="form-control text-end" step="any" required readonly>
        </td>

        <td><input type="number" id="idnds" class="form-control text-end" value="20" required min="0">
        </td>

           <td> <input type="number" id="idtotal" class="form-control text-end" step="any" required readonly>
        </th>

        <td class="text-end"><button class="btn btn-secondary btn-sm" type="submit" id="save-string">Записать</td>
</tr>
        </form>



    <tbody id="string-ost" >

{% for item in items %}
    <tr><td>{{item.title}},{{item.title.izm}}</td>
    <td class="text-end">{{item.price}}</td>
    <td class="text-end">{{item.kol}}</td>
    <td class="text-end">{{item.summa}}</td>

    <td class="text-end " >{{item.nds}}</td>
    <td class="text-end">{{item.summawithnds}}</td>
      <td  class="text-end" colspan=2 ><input data-sid={{item.pk}} data-update={{item.pk}} class="btn-string-update " value="Update" type="image" src="../static/images/edit2.png" style="width:25px;" >
<input data-sid={{item.pk}} data-del="#" class="btn-string-delete " value="Update" type="image" src="../static/images/del.png" style="width:25px;" > </td></tr>
    </tr>
    {% endfor %}

    </tbody>
        <tfoot id="idfoot"><td class="fw-bold">Итого:</td><td colspan="3" class="text-end fw-bold ">{{s}}</td><td colspan="2>" class="text-end fw-bold">{{s2}}</td> </tfoot>
</table>


</div>
</div>
</div>
<!-- Модальное окно новая номенклатура -->
<div class="modal fade" id="ModalNomPodbor" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content ">
      <div class="modal-header bg-primary text-light">
        <h5 class="modal-title  " id="exampleModalLabel"><span >Добавление номенклатуры</span></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
      </div>
      <div class="modal-body " >
          <form id="podbor-nom-form" action="#" method="post">
{% csrf_token %}
<table class="table table-bordered" >
  <thead class="bg-primary text-light">
  <th style="width:45%">Наименование</th>
   <th style="width:15%">Ед.изм.</th>
  <th style="width:20%">Категория</th>
  <th style="width:15%">Срок,мес.</th>
  </thead>
<tbody>
<tr>
    <td><input type="text" class="form-control" required id="ostpodbortitle"></td>
     <td><select class="form-control" required id="ostpodborizm">
     <option selected></option>
     {% for item in izm %}
     <option value="{{item.id}}">{{item.title}}</option>
     {% endfor %}
     </select>
     </td>
    <td><select class="form-control" id="ostpodborcategory" required>
    <option selected></option>
    {% for item in category %}
    <option value="{{item.id}}">{{item.title}}</option>
    {% endfor %}
    </select>
    </td>
    <td><input type="number" class="form-control" value="0" id="ostpodborsrok"></td>
</tr>
</tbody>
</table>

      </div>
      <div class="modal-footer">
        <button type="submit" class=" btn btn-primary" data-bs-dismiss="modal" id="savenom_modal" >Сохранить</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
  </form>
      </div>
    </div>
  </div>
</div>
{% endblock DataArea %}

whr/store/templates/store/Doc/OstDetail.html
{% extends 'store/menu.html' %}
{% load static %}
{% block DataArea %}

<div class="row">
    <div class="col-md-1  ">{{pic_label}} </div>
OstDetail

<div class="col-md-11 mx-auto shadow">


  </div>
</div>
{% endblock DataArea %}

</html>

whr/store/templates/store/Doc/Post_Ajax.html
<script>
 $('#post-form').on('submit',function(e){
event.preventDefault();
let nomerdoc=$('#id_nomerdoc').val();
let datadoc=$('#id_datadoc').val();
let postav=$('#id_postav').val();
let _csr=$("input[name=csrfmiddlewaretoken]").val();
////////////////////////////////////////////////////////////
mydata={
nomerdoc:nomerdoc,
datadoc:datadoc,
postav:postav,
csrfmiddlewaretoken:_csr,
}
///////////////////////////////////////////////////////////
$.ajax({
url:'/JurnalPost/',
method:"POST",
data:mydata,
dataType:"json",
/////////////////////////////////////////////////////////
success:function(data){
if (data.status==1){
console.log(data.unit_data);
console.log('saved');
location.href=data.url
}
}
});
//////////////////////////////////////////////////////////
 });

 //////////////////Изменение даты и номера документа, переход в журнал/////////////////
$('#post-form2').on('submit',function(e){
event.preventDefault();
let _id=$('#id_iddoc').val();
let _postav=$('#id_postav').val();
let _csr=$("input[name=csrfmiddlewaretoken]").val();
let _nomer=$('#id_nomerdoc').val();
let _data=$('#id_datadoc').val();
console.log(_postav);

mydata={
id:_id,
nomer:_nomer,
data:_data,
postav:_postav,
csrfmiddlewaretoken:_csr,
}

$.ajax({
url:'/ReturnToJurnalPost/',
method:"POST",
data:mydata,
dataType:"json",

success:function(data){
if(data.status==1){
console.log('saved record');
location.href=data.url;
}
}
});
});
///////////////////////////Редактирование документа приход//////////////////////

$('#post-doc').on('click','.btn-ost-update',function(e){
console.log('Pressed button');
let _id=$(this).attr('data-sid');
let _csr=$("input[name=csrfmiddlewaretoken]").val();

mydata={
id:_id,
csrfmiddlewaretoken:_csr,
}
$.ajax({
url:'/EditPostDoc/',
method:"POST",
data:mydata,
dataType:"json",

success:function(data){
if (data.status==1){
location.href=data.url
}
}
});
});

////////////////////////////////////Удаление документов остатков/////////////////
$('#post-doc').on('click','.btn-ost-del',function(e){
let _id=$(this).attr('data-sid');
let _csr=$("input[name=csrfmiddlewaretoken]").val();
mythis=$(this);
mydata={
id:_id,
csrfmiddlewaretoken:_csr,
}
console.log(mydata);
$.ajax({
url:'/DeleteOstDoc/',
method:"GET",
data:mydata,
dataType:"json",
success:function(data){
if(data.status==1){
$(mythis).closest("tr").fadeOut();
}
if(data.status==0){alert('Невозможно удалить документ... Сначала необходимо удалить строки документа')}
}


});
});
</script>